### ISSUE TITLE
Can't configure ExAws to use Dynamodb Local anymore

### ISSUE THREAD

**Issue by jordi-chacon** [CargoSense/ex_aws#90] opened 2015-10-20 16:50 UTC
Hi Ben,

I was using Dynamodb Local via ExAws just fine until this commit:https://github.com/CargoSense/ex_aws/commit/d68ae5f2c0cfa2facc804c8951759e55eb9fb378

I have `host: "localhost"` which seems to cause the following crash:
```
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            (stdlib) binary.erl:317: :binary.replace/4
            (ex_aws) lib/ex_aws/config.ex:67: ExAws.Config.parse_host_for_region/1
            (ex_aws) lib/ex_aws/config.ex:16: ExAws.Config.build/2
```

Is it still possible to use DynamoDB Local via ExAws? If so, how? If not, could you consider adding that option back?

Thanks!

**Comment by benwilson512** [comment] 2015-10-20 16:51
Ah yea that's odd because that's test suite uses dynamodb local and it passes without issue. Let me see if I can figure out what the issue is one sec.

**Comment by benwilson512** [comment] 2015-10-20 16:58
Can you post the relevant parts of your config.exs and dev.exs files please?

**Comment by jordi-chacon** [comment] 2015-10-20 17:01
Here you go:

```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  http_client: HTTPoison

config :ex_aws, :dynamodb,
  scheme: {:system, "DYNAMODB_SCHEME"},
  host: {:system, "DYNAMODB_HOST"},
  port: {:system, "DYNAMODB_PORT"},
  region: "eu-west-1"
```

The error happens when trying to start my application when running `mix test` like this:
```
DYNAMODB_SCHEME="http://" \
  DYNAMODB_HOST="localhost" \
  DYNAMODB_PORT="7000" \
  mix test --include external:true
```

**Comment by benwilson512** [comment] 2015-10-20 17:58
Ah yeah I see the issue, this is my bad. I can do a fix, but for the moment a workaround would be to do

```
```

**Comment by benwilson512** [comment] 2015-10-20 17:59
I would make sure not to alter the host key at all in your prod.exs file.

**Comment by benwilson512** [comment] 2015-10-20 18:11
Can you alter your ex_aws dependency to read
```
 {:ex_aws, github: "cargosense/ex_aws", branch: "bug-fixes"}
```
as well as return your config to how it was and let me know if that fixes it?

I'll have a release out shortly if so.

**Comment by benwilson512** [comment] 2016-01-06 15:30
Gonna close this as I believe it's fixed on master.

**Closed by benwilson512** 2016-01-06 15:30 UTC

**Comment by jordi-chacon** [comment] 2016-03-02 09:13
Hi Ben,

very sorry for not getting back to you regarding this.

I just updated to ex_aws 0.4.18 and this `host: {:system, "DYNAMODB_HOST"}` still doesn't work.

I can see in module config.ex that this is intentional, i.e. you do `retrieve_runtime_value/2` for everything except for `:host`.

```  def retrieve_runtime_config(%{config: config} = client) do
    new_config = config
    |> Enum.reduce(%{}, fn
      {:host, host}, config ->
        Map.put(config, :host, host)
      {k, v}, config ->
        case retrieve_runtime_value(v, client) do
          %{} = result -> Map.merge(config, result)
          value -> Map.put(config, k, value)
        end
    end)

    %{client | config: new_config}
  end
```

This is problematic for me. I'll try to explain why:

We want to be able to create a `test` release (with `MIX_ENV=test` and `exrm`) that we can run both against the real DynamoDB and against DynamoDB Local for testing purposes. When booting the system through said release, our test scripts first define the appropriate environment variables to point to either DynamoDB or DynamoDB Local. Thus, in `config/test.exs` I need to be able to express `{:system, "DYNAMODB_HOST"}` for this to work.

I have locally removed `{:host, host}, config ->` clause from `retrieve_runtime_config/2` and now it works.

What is your take on removing it?

Thank you Ben!

**Comment by sylverlion** [comment] 2016-05-19 10:01
Hi Ben,

I just hit the same problem here, it would be great if you could fix it, this is a big issue for local development/testing purposes

I'm a bit worried to not see any answer since March 2nd, this is a great project which need support.

Thanks
