### ISSUE TITLE
InvalidSignatureException

### ISSUE THREAD

**Issue by env0der** [CargoSense/ex_aws#366] opened 2017-02-26 17:57 UTC
Hi, I have troubles using this library :-/

Here is what I have in my config:

```
config :ex_aws,
  debug_requests: true,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, {:awscli, "default", 30}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, {:awscli, "default", 30}, :instance_role],
  region: "eu-west-1"
```

and when trying to do this:

```
iex(1)> ExAws.SQS.list_queues |> ExAws.request
```

I'm getting this:

```
{:error,
 {:http_error, 403,
  %{body: "<InvalidSignatureException>\n  <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/\n\ncontent-type:application/x-www-form-urlencoded, application/x-www-form-urlencoded\nhost:sqs.eu-west-1.amazonaws.com, sqs.eu-west-1.amazonaws.com\nx-amz-date:20170226T175448Z\n\ncontent-type;host;x-amz-date\nd2a8923425e57ac809140923e28f7a1ffcc6b14c7dcc4219e6a09e53614a65d9'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20170226T175448Z\n20170226/eu-west-1/sqs/aws4_request\n7386dd439f26f20ce952c119ca699a81a3e5e7f3ca0b331cd2d40f5c21732dbe'\n</Message>\n</InvalidSignatureException>\n",
    headers: [{"Server", "Server"}, {"Date", "Sun, 26 Feb 2017 17:54:48 GMT"},
     {"Content-Type", "null"}, {"Content-Length", "765"},
     {"Connection", "close"},
     {"x-amzn-RequestId", "00f30299-ba5a-5aa5-bb57-53b4a2f2a49a"}],
    status_code: 403}}}
```

Here is a canonical string being generated by the library:

```
POST
/

content-type:application/x-www-form-urlencoded
host:sqs.eu-west-1.amazonaws.com
x-amz-date:20170226T175448Z

content-type;host;x-amz-date
d2a8923425e57ac809140923e28f7a1ffcc6b14c7dcc4219e6a09e53614a65d9
```

And here are the debug logs (I've replaced my AWS_ACCESS_KEY_ID with ***):

```
[debug] Request URL: "https://sqs.eu-west-1.amazonaws.com/"
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=***/20170226/eu-west-1/sqs/aws4_request,SignedHeaders=content-type;host;x-amz-date,Signature=489b52232ce5549fd8d55203c94a0c5b95e1ac68885c5b7c044c897a7f220dd0"}, {"host", "sqs.eu-west-1.amazonaws.com"}, {"x-amz-date", "20170226T175448Z"}, {"content-type", "application/x-www-form-urlencoded"}]
[debug] Request BODY: "Action=ListQueues"
```

I'm seeing correct AWS_ACCESS_KEY_ID in request header so I assume that AWS credentials were correctly read from my `~/.aws/credentials` file. What am I doing wrong? 

Thank you!

**Comment by jayjun** [comment] 2017-02-27 12:11
Same here with S3. I get `<Code>SignatureDoesNotMatch</Code>` when I do,

```elixir
iex> ExAws.S3.list_buckets() |> ExAws.request()
```

I've tried multiple IAM roles, including root.

Here's my minimal S3 app. https://github.com/jayjun/s3_app.git

Full error here:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
  <AWSAccessKeyId>***</AWSAccessKeyId>
  <StringToSign>AWS4-HMAC-SHA256\n20170227T114305Z\n20170227/ap-southeast-1/s3/aws4_request\nc5d5461d12f4a5a3111d7977fe09fb9a092ab1971e50d07f4b2f39d6a85f7177</StringToSign>
  <SignatureProvided>3a1b5a8994a8b508d34e1fba8c931b16eb74dc26b8779b43bb62a50f440925b6</SignatureProvided>
  <StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 31 37 30 32 32 37 54 31 31 34 33 30 35 5a 0a 32 30 31 37 30 32 32 37 2f 61 70 2d 73 6f 75 74 68 65 61 73 74 2d 31 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 63 35 64 35 34 36 31 64 31 32 66 34 61 35 61 33 31 31 31 64 37 39 37 37 66 65 30 39 66 62 39 61 30 39 32 61 62 31 39 37 31 65 35 30 64 30 37 66 34 62 32 66 33 39 64 36 61 38 35 66 37 31 37 37</StringToSignBytes>
  <CanonicalRequest>GET\n/\n\ncontent-length:0\nhost:s3-ap-southeast-1.amazonaws.com, s3-ap-southeast-1.amazonaws.com\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20170227T114305Z\n\ncontent-length;host;x-amz-content-sha256;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</CanonicalRequest>
  <CanonicalRequestBytes>47 45 54 0a 2f 0a 0a 63 6f 6e 74 65 6e 74 2d 6c 65 6e 67 74 68 3a 30 0a 68 6f 73 74 3a 73 33 2d 61 70 2d 73 6f 75 74 68 65 61 73 74 2d 31 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 2c 20 73 33 2d 61 70 2d 73 6f 75 74 68 65 61 73 74 2d 31 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3a 65 33 62 30 63 34 34 32 39 38 66 63 31 63 31 34 39 61 66 62 66 34 63 38 39 39 36 66 62 39 32 34 32 37 61 65 34 31 65 34 36 34 39 62 39 33 34 63 61 34 39 35 39 39 31 62 37 38 35 32 62 38 35 35 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 32 30 31 37 30 32 32 37 54 31 31 34 33 30 35 5a 0a 0a 63 6f 6e 74 65 6e 74 2d 6c 65 6e 67 74 68 3b 68 6f 73 74 3b 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3b 78 2d 61 6d 7a 2d 64 61 74 65 0a 65 33 62 30 63 34 34 32 39 38 66 63 31 63 31 34 39 61 66 62 66 34 63 38 39 39 36 66 62 39 32 34 32 37 61 65 34 31 65 34 36 34 39 62 39 33 34 63 61 34 39 35 39 39 31 62 37 38 35 32 62 38 35 35</CanonicalRequestBytes>
  <RequestId>8BD366B04407597A</RequestId>
  <HostId>w6nh7AUDmov6/bT2dTkjbppnZ0Tz4UvMd4y0TsQ0/F3AkfcWIY77VXFyIrFNesKcApOiMY+a+9o=</HostId>
</Error>

**Comment by jayjun** [comment] 2017-02-27 16:25
I've isolated the problem. ExAws sends `host:s3.amazonaws.com` but `CanonicalRequest` expects `host:s3.amazonaws.com, s3.amazonaws.com`.

Sent:
```
GET\n/\n\ncontent-length:0\nhost:s3.amazonaws.com\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20170227T142117Z\n\ncontent-length;host;x-amz-content-sha256;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

CanonicalRequest:
```
GET\n/\n\ncontent-length:0\nhost:s3.amazonaws.com, s3.amazonaws.com\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20170227T142117Z\n\ncontent-length;host;x-amz-content-sha256;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

**Comment by benwilson512** [comment] 2017-02-27 16:28
This is very strange. What version are you on?

**Comment by benwilson512** [comment] 2017-02-27 16:30
Are you able to list the contents of a bucket? or does this happen with requests on buckets as well?

**Comment by env0der** [comment] 2017-02-27 16:40
@benwilson512 I'm using `1.1.0` and I also have the same problem with S3 as @jayjun.

**Comment by robmadole** [comment] 2017-02-27 16:51
Going to +1 this for me too. Same problem with S3.

**Comment by benwilson512** [comment] 2017-02-27 16:55
Is this just for listing buckets, or is this for all operations?

**Comment by jayjun** [comment] 2017-02-27 16:57
This is for listing buckets only. I'm on,
- ExAws 1.1.0
- hackney 1.6.6
- Poison 3.1.0
- SweetXml 0.6.5

When I patch `host` to match `CanonicalRequest` (i.e. `host:s3.amazonaws.com, s3.amazonaws.com`, I get,
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchBucket</Code>
  <Message>The specified bucket does not exist</Message>
  <BucketName>s3.amazonaws.com, s3.amazonaws.com</BucketName>
  <RequestId>D1B13EB239317D61</RequestId>
   <HostId>y2Cshrxt3OSNFa2VefKRoDCfwHuj9vHdw3uTkfJZ8rYvpcZg2M5wAszDUr7qdQeG1T7Gq04wwK0=</HostId>
</Error>
```

**Comment by robmadole** [comment] 2017-02-27 17:04
I'm wondering if it's hackney. We are also on 1.6.6 and it's looking like that's where the regression occurred. I'm confirming now. @benwilson512 we are calling `S3.get_object/2`.

**Comment by benwilson512** [comment] 2017-02-27 17:19
Can you try switching to hackney 1.6.5?

**Comment by robmadole** [comment] 2017-02-27 17:21
Yep, working on that now.

**Comment by jayjun** [comment] 2017-02-27 17:44
There's an issue on duplicate HTTP header values (benoitc/hackney#58) with the exact pattern.

**Comment by benwilson512** [comment] 2017-02-27 17:46
Hurg. And people wonder why I had exact hackney versions listed for a while. I'm done doing `~>` for hackney.

**Comment by robmadole** [comment] 2017-02-27 18:01
I can confirm this too. I switched from 1.6.6 to 1.6.5 and it resolves the issue.

**Comment by benwilson512** [comment] 2017-02-27 18:04
Right so the question is, am I somehow having duplicate content type headers (bug on our end) or is hackney somehow adding another header (bug on their end).

**Comment by benwilson512** [comment] 2017-02-27 18:05
Should be easy to check. if you turn on `debug_requests: true` what headers do you see?

**Comment by env0der** [comment] 2017-02-27 18:05
Downgrading hackney to 1.6.5 has also resolved my problem.

**Comment by jayjun** [comment] 2017-02-27 18:11
`debug_requests` shows the correct headers. The problem is benoitc/hackney@29eae2bfc9abbb8015a308a3aebdf0776b9d9bee appends to the `host` that ExAws  adds.

I'm not sure if [`maybe_add_host`](https://github.com/benoitc/hackney/blob/9caf8c612d2408498b95da550755c4ab71e48ac2/src/hackney_request.erl#L617) is supposed to prevent that.

**Comment by venkatd** [comment] 2017-02-28 16:23
Confirming that ex_aws 1.1.0 works with hackney 1.6.5.

**Comment by jayjun** [comment] 2017-03-02 00:41
Fixed in hackney 1.7.0. See benoitc/hackney#390.

**Closed** 2017-03-02 00:42 UTC

**Comment by ryanbillingsley** [comment] 2017-03-06 21:03
It would be great if this could be added to the README, just struggled for a bit trying to get this to work, @jayjun suggesting to use 1.7 fixed it for me

**Comment by gchronis** [comment] 2017-03-15 23:01
@benwilson512  Confirming that this bug was not just for S3. Reaching SQS with ex_aws 1.1 and hackney 1.6.6 got the same error.

**Comment by benwilson512** [comment] 2017-03-15 23:12
Yup I know, Hackney 1.6.6 broke basically all requests.
