### ISSUE TITLE
All DynamoDB requests time out

### ISSUE THREAD

**Issue by jordi-chacon** [CargoSense/ex_aws#42] opened 2015-06-26 16:04 UTC
Hi!

First of all, thank you so much for putting so much time and dedication into this library. I truly appreciate it! I think it's awesome that you made it possible to get the credentials via the EC2 role!

I am facing some problems when running my Elixir application from within an EC2 instance inside an ECS container. All requests time out.

This is my ex_aws config:
```
[dynamodb: [
  scheme: {:system, "DYNAMODB_SCHEME"},
  host: {:system, "DYNAMODB_HOST"},
  port: {:system, "DYNAMODB_PORT"},
  region: "eu-west-1"
],
included_applications: [],
access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]]
```

The last two OS env variables are undefined, so the :instance_role is used.

I have put an IO.inspect on ExAws.Request.request/5 to better understand what might be the problem:

Body of the request:
```
%{"AttributeDefinitions" => [%{"AttributeName" => :uid,
     "AttributeType" => "S"}],
  "KeySchema" => [%{"AttributeName" => "uid", "KeyType" => "HASH"}],
  "ProvisionedThroughput" => %{"ReadCapacityUnits" => 1,
    "WriteCapacityUnits" => 1}, "TableName" => "facebook_service_users"}
```

Headers:
```
[{"Authorization",
  "AWS4-HMAC-SHA256 Credential=/20150626/eu-west-1/dynamodb/aws4_request,SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date;x-amz-target,Signature=668....f"},
 {"host", "dynamodb.eu-west-1.amazonaws.com"},
 {"x-amz-date", "20150626T155125Z"},
 {"x-amz-target", "DynamoDB_20120810.CreateTable"},
 {"content-type", "application/x-amz-json-1.0"}, {"x-amz-content-sha256", ""}]
```

URL:
```
https://dynamodb.eu-west-1.amazonaws.com:80/
```

This is the error I get in the logs:
```
ExAws: HTTP ERROR: :connect_timeout
```

Just to rule out that the problem is not in the IAM side, I have tried to create a dynamodb table from the EC2 instances via awscli and that worked just fine. Therefore, the problem is at the application level.

I am running my application with MIX_ENV=test.

I would appreciate it if you would share with me any hints on what could be the problem.

Thank you a lot!

**Comment by jordi-chacon** [comment] 2015-06-28 06:59
I have fixed the timeout problem by sending the requests to https://dynamodb.eu-west-1.amazonaws.com:443/ instead.

Now I have a different problem. My requests failed to authenticate:
```
{error,
  {<<\"UnrecognizedClientException\">>,
   <<\"The security token included in the request is invalid.\">>}}
```

I have printed the key and the secret and they look correct. They are fetched from the instance meta-data just fine.

Any hints on what could be the problem?

**Comment by benwilson512** [comment] 2015-06-29 13:52
Hey sorry I'm just not getting to this. So the issue related to the ports is partially my fault, partially not. HTTPs uses port 443 not port 80, so it isn't surprising that 80 didn't work. You could actually just leave off specifying the port entirely because then the URL would be simply `"https://dynamodb.eu-west-1.amazonaws.com"` and that will route to the correct port.

Basically, if the port is a numerical `80` then I don't put it as part of the URL at all. This is why the config may say port 80 for https but still work anyway, it gets stripped when the URLs are generated. This is clearly confusing behavior and I plan on doing something about it.

Unfortunately I'm not sure why that's the error you're getting. Try specifying the port as a numerical `80` which will drop it from the URL. I wonder if including the port number is munging up the AWS request signing process.

**Comment by jordi-chacon** [comment] 2015-06-29 17:21
Hi!

Thanks for your reply.

I have specified the port as numerical 80 in config.exs as well as schema "http://". The url sent to ExAws.Request is now "http://dynamodb.eu-west-1.amazonaws.com/". So no port there as you said. Still getting the same error though :/

Is there anything else that I could debug that could hint us what the problem is?

**Comment by benwilson512** [comment] 2015-06-29 17:25
Hey, I didn't intend for you to change the schema. HTTPoison (the http client library) is smart enough to use the correct port when the request is actually sent via HTTP. I simply want the port out of the signing process. Try with a schema of "https://" and a port of numerical 80.

On a different angle, the error you're getting seems to have to do with authentication, but isn't about signing errors. This seems to indicate that there may be permission issues with the IAM credentials. Have you used the AWS IAM simulator to determine if that role is able to execute the requests you want?

**Comment by jordi-chacon** [comment] 2015-06-29 17:36
The IAM simulator says the operation is allowed. All DynamoDB operations are allowed by my policy. Furthermore, I have sent such requests from both inside the EC2 instance and from inside an ECS container via awscli.

**Comment by benwilson512** [comment] 2015-06-29 17:37
Awesome good to know, we'll figure it out. Any luck with `[schema: "https://", port: 80]` ?

**Comment by jordi-chacon** [comment] 2015-06-29 17:40
Just tried it, same problem.

**Comment by benwilson512** [comment] 2015-06-29 17:41
Ok. I haven't had a chance to test much on the EU region, I'll ssh into an instance this afternoon and see if I can reproduce and determine the issues.

**Comment by jordi-chacon** [comment] 2015-06-29 18:56
Thanks for your support!

I have tested running my Elixir application in an Ubuntu Server EC2 instance instead of inside an ECS container and the problem remains.

**Comment by jordi-chacon** [comment] 2015-06-29 19:31
Interesting news.

Just did another test where, before starting the Elixir application, I run
```
export AWS_ACCESS_KEY_ID=A...L
export AWS_SECRET_ACCESS_KEY=b.....a
```
using the key and secret of my admin account. This worked. The requests to dynamodb worked just fine!


I have also tried exporting those environment variables with the key and secret I get from:
```
curl http://169.254.169.254/latest/meta-data/iam/security-credentials/myrole
```

This doesn't work. These credentials are actually the ones fetched by your library if I don't export the environment variables. So the problem seems to be with the key and the secret used.

**Comment by benwilson512** [comment] 2015-06-29 19:33
Well that's certainly a relief on my end. Only thing I can recommend is to fiddle around with with the IAM simulator until you can reproduce the issue with the role / keys. Best of luck!

**Comment by jordi-chacon** [comment] 2015-06-29 20:11
This is very strange.

Without running `aws configure`, this works:
```
aws dynamodb create-table --region eu-west-1 --table-name test_table --attribute-definitions AttributeName=uid,AttributeType=S --key-schema AttributeName=uid,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1
```

If this works, shouldn't the requests coming from ex_aws also work?

**Comment by benwilson512** [comment] 2015-06-29 20:13
Use `set` to determine if your environment variables are still set. `aws` will use those first.

**Comment by jordi-chacon** [comment] 2015-06-29 20:16
I run this on a fresh new EC2 instance. I have not copied my admin credentials to this one.

**Comment by benwilson512** [comment] 2015-06-29 20:19
So let me see if I can recap:
- `aws dynamodb $stuff`: works
- `curl myrole` + setting environment variables based on that result: doesn't work
- ExAws configured to use instance_role: doesn't work

The fact that the second option doesn't work is super weird. Let me see if I can reproduce.

**Comment by jordi-chacon** [comment] 2015-06-29 20:23
The recap is correct.

My EC2 instance is running ubuntu-trusty-14.04-amd64-server-20150325 (ami-47a23a30).

This EC2 instance has a role with the "Managed Policy" "AmazonDynamoDBFullAccess".

**Comment by jordi-chacon** [comment] 2015-06-29 20:46
I'm a n00b in AWS, so I might be misunderstanding this statement, but it say that we should include a session token, which we don't seem to do.

"When you make a call using temporary security credentials, the call must include a session token, which is returned along with those temporary credentials. AWS uses the session token to validate the temporary security credentials."

http://docs.aws.amazon.com/STS/latest/UsingSTS/using-temp-creds.html

**Comment by benwilson512** [comment] 2015-06-29 20:48
You may well be right there. This hasn't been a feature I've had a chance to test much I'm afraid. Investigating.

**Comment by benwilson512** [comment] 2015-06-29 21:06
I've been able to reproduce. I believe you're correct about the cause. Fixing.

**Comment by jordi-chacon** [comment] 2015-06-29 21:09
Cool!

Yes, I think we need to add a header called `X-Amz-Security-Token` with the value of the `Token` field in the security credentials.

**Comment by benwilson512** [comment] 2015-06-29 21:28
This should be fixed on master now. Will do a release shortly. I've tested it myself, but please confirm that it looks ok on your end as well.

**Closed** 2015-06-29 21:27 UTC
Labels: question

**Comment by jordi-chacon** [comment] 2015-06-29 22:55
It works!!! :smiley:
Thank you so much for your dedication Ben.
