### ISSUE TITLE
DynamoDB calls adding as much as 3x latency to hackney requests

### ISSUE THREAD

**Issue by asgoel** [CargoSense/ex_aws#388] opened 2017-03-24 20:36 UTC
Hey there,

I'm trying to do a simple latency test in an application that is making 10,000 query calls to Dynamo in a `Task.async_stream` with a `max_concurrency` of 100. It was looking pretty slow so I decided to dig deeper and noticed that for a given query call, the generation of all the request parameters can take up to 2-3 times as long as making the actual hackney request. For example, if the hackney request took 45ms, I was seeing logs where the total query call could take up to 140ms. Where in `ex_aws` should I look for a bottleneck that could lead to this? For reference, I'm running this on an ec2 instance with 2 vCPUs, and using the instance metadata url, not a credentials file or credentials env vars.

Thanks!

**Comment by benwilson512** [comment] 2017-03-24 21:12
Hey there! I'm happy to look into it, but to do so I'll need some more information. What version of elixir are you on? Can you provide a reproduceable example?

**Comment by asgoel** [comment] 2017-03-24 22:53
Running v1.4.0. Here's an example below (without timing the individual queries):

```
users = ["user_1", "user_2", ..., "user_10000"]
stream = Task.async_stream(users, fn user ->
   _ = ExAws.Dynamo.query("dynamo_table_here",
                                             key_condition_expression: "user_id = :v1",
                                             index_name: "user-index",
                                             expression_attribute_values: %{"v1" => user}) |> ExAws.request
end, max_concurrency: 100)
start_time = :os.system_time(:millisecond)
Enum.to_list(stream)
end_time = :os.system_time(:millisecond)
IO.puts "#{(end_time - start_time)}"
```

Let me know if that works. Thanks!

**Comment by benwilson512** [comment] 2017-03-24 22:56
Well I mean there's a lot going on here, if you aren't timing an individual call I'm not sure how you're confident that it's additional latency. In fact the only Dynamo specific overhead that ExAws is gonna add it literally just the time it takes to do

```
ExAws.Dynamo.query("dynamo_table_here",
                                             key_condition_expression: "user_id = :v1",
                                             index_name: "user-index",
                                             expression_attribute_values: %{"v1" => user})
```
I would time that and then figure out if that's actually your issue.

Keep in mind that Dynamo is heavily rate limited, it's basically the main thing you pay for.

**Comment by asgoel** [comment] 2017-03-24 23:16
Sure, what I timed was the time directly before and after the ExAws dynamo call, and then the time directly before and after the hackney call in lib/ex_aws/request/hackney, and compared them.

I'll keep investigating and see if anything pops up, but was just wondering if there was anything specific in the stack from when the ExAWS call gets made to when the hackney request gets made that could be super slow.

**Comment by asgoel** [comment] 2017-03-24 23:17
re: Dynamo being rate limited, I basically wrote the same code in python using gevent and didn't really have a problem. But again could have just been the circumstances at the time.  That's the constant problem with AWS :( Never know if the situation is 100% reproducible when it comes to latency.

**Comment by benwilson512** [comment] 2017-03-24 23:19
In the example you gave me what you timed was directly before and after 1000 calls made 100 at a time concurrently. I'm happy to help with a problem but I need a concrete, isolated, reproducible instance of slowness.

It's entirely possible that something is misbehaving here but it's more likely to be hackney's pooling construct than anything else. I'm pretty sure for example that the hackney pool is by default only like 30 or 50 workers, so doing 100 concurrency is guaranteed to fight over that.

Rate limits: did you check on the dynamodb UI and look to see if you were exceeding the provisioned throughput?

**Comment by asgoel** [comment] 2017-03-25 01:44
Throughput not an issue as far as I can tell - our provisioned read capacity is 500 and each test just puts a small blip up towards 100.

As far as exact timing, goes, I updated the sample above to where I had the additional timing statements:

```
```
users = ["user_1", "user_2", ..., "user_10000"]
stream = Task.async_stream(users, fn user ->
  s = :os.system_time(:milliseconds)
   _ = ExAws.Dynamo.query("dynamo_table_here",
                                             key_condition_expression: "user_id = :v1",
                                             index_name: "user-index",
                                             expression_attribute_values: %{"v1" => user}) |> ExAws.request
  e = :os.system_time(:milliseconds)
  IO.puts "DYNAMO: #{(e - s)}"
end, max_concurrency: 100)
start_time = :os.system_time(:millisecond)
Enum.to_list(stream)
end_time = :os.system_time(:millisecond)
IO.puts "#{(end_time - start_time)}"
```

I put another timing statement in this file: https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/request/hackney.ex#L19. Right before the hackney request is made, and right after the request is made, and print out the difference if the url contains the string "dynamo" (to weed out any other possible calls). 

Since this morning its gotten a bit faster, but still seeing the overall query take about 2x as long as the hackney request (so more like 45ms for the pure hackney request, 90ms for the entire dynamo ex_aws call).

**Comment by benwilson512** [comment] 2017-03-25 01:50
Does this happen when doing a single call or only when doing the stream?

**Comment by asgoel** [comment] 2017-03-25 02:00
doesn't seem to happen when I do a single request. The overall time of the entire SDK call is pretty close to my hackney request. In general, the timing on my hackney requests when I do 10,000 requests one-by-one is much faster (I'm able to get almost all requests to complete in 4-5 ms, and the entire SDK call to complet ein 5-6 milliseconds). I'm using `pool: :default` as part of my `hackney_opts` for ex_aws. Maybe I should be creating a bigger pool?

**Comment by benwilson512** [comment] 2017-03-25 02:55
I'm convinced this is pool related, ExAws encoding isn't gonna change by 45ms with concurrency. As I mentioned earlier the default pool size is much smaller than 100 so you should either disable the pool or make it larger.

**Comment by asgoel** [comment] 2017-03-25 02:58
ok. will try that. if you're convinced thats the only thing, then feel free to close. This isn't a hugely important issue but just something I thought I would bring up to check.

**Comment by asgoel** [comment] 2017-03-25 03:17
Another thing that I forgot to note but definitely should have: when I run something like `dstat` alongside the stream query (even with a hackney pool of size 100), i pretty much consistently get 85-90% CPU usage, which probably means that executing this on 2 cores is way more CPU bound than network bound, which is a function of the erlang VM itself, and I'm guessing nothing that we can change in ex_aws to make it better. Going to try on a bigger instance and see what happens....

**Comment by benwilson512** [comment] 2017-03-25 10:46
I would use `:observer` to look at performance not something like dstat. If you have multiple cores 90% is nowhere close to CPU bound since Erlang is gonna use all of your cores.

You'll want to check the process list tab in :observer to see if any process has a large message queue, that'll be your bottleneck.

**Comment by benwilson512** [comment] 2017-03-25 10:47
You could also easily stub the HTTP adapter and instead of calling out to hackney, simply return a simple response message.

**Comment by benwilson512** [comment] 2017-03-28 13:54
Closing for now due to lack of information, feel free to re-open if you come across an isolated example.

**Closed by benwilson512** 2017-03-28 13:54 UTC
