### ISSUE TITLE
400 Bad Request using ExAws.S3.presigned_url/4 to PUT file with IAM Role temporary credentials

### ISSUE THREAD

**Issue by ericlathrop** [CargoSense/ex_aws#228] opened 2016-09-26 15:31 UTC
I'm using this code:
```elixir
    {:ok, url} = ExAws.Config.new(:s3)
                 |> ExAws.S3.presigned_url(:put, "my-bucket", "#{some_id}.jpg")
```
to generate a URL to upload an image to S3. It works locally when I specify the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables on the command line.

When I deploy my app, the machine has an IAM Role with this policy:
```json
{"Version":"2012-10-17","Statement":[{"Action":["s3:PutObject"],"Resource":["arn:aws:s3:::my-bucket/*"],"Effect":"Allow"}]}
```
and I get a `400 Bad Request` response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>InvalidToken</Code>
<Message>The provided token is malformed or otherwise invalid.</Message>
<Token-0> ... long string ... </Token-0>
<RequestId> ... </RequestId>
<HostId> ... </HostId>
</Error>
```

The main difference between the working and broken requests seems to be the addition of the `X-Amz-Security-Token` query string parameter, which is what it's complaining  about in the `<Token-0>` XML above. I'm guessing the token is encoded/transformed incorrectly somewhere. I don't want to paste the actual token here, but it includes the characters `A-Z`, `a-z`, `0-9`,  ` ` (space),  `/`, and ends with an `=`.

**Comment by benwilson512** [comment] 2016-09-30 13:48
Duplicate of #207 however this one is more detailed. #233 probably fixes, will be evaluating today.

**Comment by benwilson512** [comment] 2016-10-01 14:37
Fixed in rc.1

**Closed by benwilson512** 2016-10-01 14:37 UTC

**Comment by ManojKumarHC** [comment] 2019-09-23 11:28
I am getting 400 Bad Request ,  Response message says  **Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified**

But I am not calling the Two times auth mechanism . Below given My code .. kindly help to solve this issue  .. i am searching over internet from couple of days . not finding any proper solution 

---------------To get Presigned URL ---------------- 

        AWS.config.region = 'ap-south-1';
        AWS.config.signatureVersion = 'v4';
        AWS.config.update({ accessKeyId: <accesskey>, secretAccessKey: <secretaccesskey> });

        var s3 = new AWS.S3();
        var params = {Bucket: <bucket>, Key: orderJson.name ,  Expires: 100000, ACL: 'bucket-owner-full-control', ContentType:orderJson.type}
        s3.getSignedUrl('putObject', params, function(err, url) {
            if ( err ) console.log( err );
            console.log( 'ur', url )
          var sta = {url: url}
            cb( undefined,  sta);
   } );

-----------------Client side  ---------------------------------
var mk = $( "#multipleFileSelect" )[0].files[0];
                var dat = { name: mk.name, size: mk.size, type: mk.type }
         Service.Upload(dat).then(function(result) {
                    // Mark as success
                  //  file.Success = true;
                        console.log( 'rs', result )

                    var req = { 
                        url: result.url,
                            method: 'PUT',
                        data: mk,
                        processData: false,
                        contentType: mk.type,
                        }
                        console.log('req' , req)
                        
                    $http( req ).then( function ( res ) { console.log( res ) },
                        function ( err ) { console.log( 'errrr', err ) } );
   }, function ( error ) {
                    // Mark the error
                    $scope.Error = error;
                    } );

------------------------------------------------------------------------
attached the screenshot ... help me to resolve this  

Regards,
Manoj
![Screenshot (235)](https://user-images.githubusercontent.com/24651237/65422173-5dc62880-de23-11e9-8a7c-3182949a49bd.png)
